require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TribesController do

  # This should return the minimal set of attributes required to create a valid
  # Tribe. As you add validations to Tribe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TribesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tribes as @tribes" do
      tribe = Tribe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tribes).should eq([tribe])
    end
  end

  describe "GET show" do
    it "assigns the requested tribe as @tribe" do
      tribe = Tribe.create! valid_attributes
      get :show, {:id => tribe.to_param}, valid_session
      assigns(:tribe).should eq(tribe)
    end
  end

  describe "GET new" do
    it "assigns a new tribe as @tribe" do
      get :new, {}, valid_session
      assigns(:tribe).should be_a_new(Tribe)
    end
  end

  describe "GET edit" do
    it "assigns the requested tribe as @tribe" do
      tribe = Tribe.create! valid_attributes
      get :edit, {:id => tribe.to_param}, valid_session
      assigns(:tribe).should eq(tribe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tribe" do
        expect {
          post :create, {:tribe => valid_attributes}, valid_session
        }.to change(Tribe, :count).by(1)
      end

      it "assigns a newly created tribe as @tribe" do
        post :create, {:tribe => valid_attributes}, valid_session
        assigns(:tribe).should be_a(Tribe)
        assigns(:tribe).should be_persisted
      end

      it "redirects to the created tribe" do
        post :create, {:tribe => valid_attributes}, valid_session
        response.should redirect_to(Tribe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tribe as @tribe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tribe.any_instance.stub(:save).and_return(false)
        post :create, {:tribe => {}}, valid_session
        assigns(:tribe).should be_a_new(Tribe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tribe.any_instance.stub(:save).and_return(false)
        post :create, {:tribe => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tribe" do
        tribe = Tribe.create! valid_attributes
        # Assuming there are no other tribes in the database, this
        # specifies that the Tribe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tribe.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tribe.to_param, :tribe => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tribe as @tribe" do
        tribe = Tribe.create! valid_attributes
        put :update, {:id => tribe.to_param, :tribe => valid_attributes}, valid_session
        assigns(:tribe).should eq(tribe)
      end

      it "redirects to the tribe" do
        tribe = Tribe.create! valid_attributes
        put :update, {:id => tribe.to_param, :tribe => valid_attributes}, valid_session
        response.should redirect_to(tribe)
      end
    end

    describe "with invalid params" do
      it "assigns the tribe as @tribe" do
        tribe = Tribe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tribe.any_instance.stub(:save).and_return(false)
        put :update, {:id => tribe.to_param, :tribe => {}}, valid_session
        assigns(:tribe).should eq(tribe)
      end

      it "re-renders the 'edit' template" do
        tribe = Tribe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tribe.any_instance.stub(:save).and_return(false)
        put :update, {:id => tribe.to_param, :tribe => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tribe" do
      tribe = Tribe.create! valid_attributes
      expect {
        delete :destroy, {:id => tribe.to_param}, valid_session
      }.to change(Tribe, :count).by(-1)
    end

    it "redirects to the tribes list" do
      tribe = Tribe.create! valid_attributes
      delete :destroy, {:id => tribe.to_param}, valid_session
      response.should redirect_to(tribes_url)
    end
  end

end
